name: coffe_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  http: ^1.2.1
  meta: ^1.11.0
  scrollable_positioned_list: ^0.3.8
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  flutter_cache_manager: ^3.3.1
  yandex_mapkit: ^4.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  sqlite3: ^2.4.3
  flutter_local_notifications: ^9.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
